---
title: "TP 3"
author: "Ignacio Evangelista"
date: 2020/08/23
materia: "Análisis Multivariado"
fecha: "Septiembre 2020"
output: 
  pdf_document:
    keep_tex: true
    latex_engine: xelatex

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = 'H', fig.align = "center")
knitr::opts_chunk$set(out.extra = '',fig.showtext = TRUE)

knitr::knit_hooks$set(source = function(x, options) {
    paste("\\begin{lstlisting}[style=codechunk]\n", x, 
      "   \n   \\end{lstlisting}", sep = "")
})

library(dplyr)
library(ggplot2)
library(kableExtra)
library(forcats)
library(ggrepel)
library(purrr)
library(tidyr)
library(Morpho)
library(FactoMineR)
library(ggtext)

library(showtext)
showtext_auto()
font_add_google(name="Noto Sans", family = "noto")
theme_set(theme_bw(base_family = "noto"))
```

# Actividades Teóricas

*Demostrar que las matrices $\mathbf{R}\mathbf{R}’$ y $\mathbf{R}’\mathbf{R}$, siendo $\mathbf{R}$ una matriz rectangular o cuadrada de elementos reales, tienen los mismos valores propios*

Si se representan estas variables y las suplementarias en las direcciones obtenidas, se obtiene el gráfico de la Figura \ref{fig:proyecciones1}. Una conclusión que se extrae es que buenos desempeños en los problemas de proporciones, probabilidades, lógica y control de variables se dan con frecuencia juntos mientras que no hay asociación de estos con los problemas combinatorios. Por otra parte, las variables **sexo** y **carrera** no están bien representadas en general por ninguno de los ejes principales (comportamiento promedio), dando a entender que los buenos o malos desempeños en los tests propuestos no se pueden asociar fuertemente con un sexo o carrera. En otras palabras, no hay evidencia de asociación entre nivel obtenido en el test de competencias y carrera o sexo.
